FROM oven/bun:latest

WORKDIR /app

COPY . .

RUN bun install

RUN apt update && apt install -y curl

RUN bun run build

RUN export NODE_ENV=dev

CMD bash -c "if [ \"$NODE_ENV\" = \"production\" ]; then node build; else bun run dev; fi"