FROM docker.io/jitesoft/node-yarn:latest

WORKDIR /app

COPY . .

RUN yarn

RUN yarn run build

RUN export NODE_ENV=dev

CMD bash -c "if [ \"$NODE_ENV\" = \"production\" ]; then node build; else yarn run dev; fi"
