
networks:
  default:
    external:
      name: BOILDERPLATE_network

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - default
    
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - default
  
  database:
    image: postgres:13
    ports:
      - "5432:5432"