FROM oven/bun:latest

WORKDIR /app

COPY . /app

RUN bun install

RUN bun run build

ENV  NODE_ENV=dev

EXPOSE 3001

CMD bash -c "if [ \"$NODE_ENV\" = \"production\" ]; then node dist/main.js; else bun run dev; fi"