name: Build the App (docker-compose)

on:
   push:
      branches: [main]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout the code
           uses: actions/checkout@v2.3.4

         - name: Create Fake .env-File
           run: touch ./backend/.env

         - name: Build the app
           run: docker-compose build
