name: Unit Tests

on:
   push:
      branches: [main]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout the code
           uses: actions/checkout@v2.3.4

         - name: Test Frontend and Backend
           run: bash ./scripts/test.sh
